/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTestesRouteImport } from './routes/_app.testes'
import { Route as AppPessoasRouteImport } from './routes/_app.pessoas'
import { Route as AppMentoresRouteImport } from './routes/_app.mentores'
import { Route as AppGruposRouteImport } from './routes/_app.grupos'
import { Route as AppEstatisticasRouteImport } from './routes/_app.estatisticas'
import { Route as AppEnviosRouteImport } from './routes/_app.envios'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppPessoasIdRouteImport } from './routes/_app.pessoas.$id'
import { Route as AppEnviosNovoRouteImport } from './routes/_app.envios.novo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTestesRoute = AppTestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasRoute = AppPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AppRoute,
} as any)
const AppMentoresRoute = AppMentoresRouteImport.update({
  id: '/mentores',
  path: '/mentores',
  getParentRoute: () => AppRoute,
} as any)
const AppGruposRoute = AppGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AppRoute,
} as any)
const AppEstatisticasRoute = AppEstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => AppRoute,
} as any)
const AppEnviosRoute = AppEnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasIdRoute = AppPessoasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPessoasRoute,
} as any)
const AppEnviosNovoRoute = AppEnviosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppEnviosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/envios': typeof AppEnviosRouteWithChildren
  '/estatisticas': typeof AppEstatisticasRoute
  '/grupos': typeof AppGruposRoute
  '/mentores': typeof AppMentoresRoute
  '/pessoas': typeof AppPessoasRouteWithChildren
  '/testes': typeof AppTestesRoute
  '/envios/novo': typeof AppEnviosNovoRoute
  '/pessoas/$id': typeof AppPessoasIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/envios': typeof AppEnviosRouteWithChildren
  '/estatisticas': typeof AppEstatisticasRoute
  '/grupos': typeof AppGruposRoute
  '/mentores': typeof AppMentoresRoute
  '/pessoas': typeof AppPessoasRouteWithChildren
  '/testes': typeof AppTestesRoute
  '/': typeof AppIndexRoute
  '/envios/novo': typeof AppEnviosNovoRoute
  '/pessoas/$id': typeof AppPessoasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/envios': typeof AppEnviosRouteWithChildren
  '/_app/estatisticas': typeof AppEstatisticasRoute
  '/_app/grupos': typeof AppGruposRoute
  '/_app/mentores': typeof AppMentoresRoute
  '/_app/pessoas': typeof AppPessoasRouteWithChildren
  '/_app/testes': typeof AppTestesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/envios/novo': typeof AppEnviosNovoRoute
  '/_app/pessoas/$id': typeof AppPessoasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/envios'
    | '/estatisticas'
    | '/grupos'
    | '/mentores'
    | '/pessoas'
    | '/testes'
    | '/envios/novo'
    | '/pessoas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/configuracoes'
    | '/envios'
    | '/estatisticas'
    | '/grupos'
    | '/mentores'
    | '/pessoas'
    | '/testes'
    | '/'
    | '/envios/novo'
    | '/pessoas/$id'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/configuracoes'
    | '/_app/envios'
    | '/_app/estatisticas'
    | '/_app/grupos'
    | '/_app/mentores'
    | '/_app/pessoas'
    | '/_app/testes'
    | '/_app/'
    | '/_app/envios/novo'
    | '/_app/pessoas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/testes': {
      id: '/_app/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof AppTestesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pessoas': {
      id: '/_app/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof AppPessoasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mentores': {
      id: '/_app/mentores'
      path: '/mentores'
      fullPath: '/mentores'
      preLoaderRoute: typeof AppMentoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grupos': {
      id: '/_app/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AppGruposRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estatisticas': {
      id: '/_app/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof AppEstatisticasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/envios': {
      id: '/_app/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof AppEnviosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pessoas/$id': {
      id: '/_app/pessoas/$id'
      path: '/$id'
      fullPath: '/pessoas/$id'
      preLoaderRoute: typeof AppPessoasIdRouteImport
      parentRoute: typeof AppPessoasRoute
    }
    '/_app/envios/novo': {
      id: '/_app/envios/novo'
      path: '/novo'
      fullPath: '/envios/novo'
      preLoaderRoute: typeof AppEnviosNovoRouteImport
      parentRoute: typeof AppEnviosRoute
    }
  }
}

interface AppEnviosRouteChildren {
  AppEnviosNovoRoute: typeof AppEnviosNovoRoute
}

const AppEnviosRouteChildren: AppEnviosRouteChildren = {
  AppEnviosNovoRoute: AppEnviosNovoRoute,
}

const AppEnviosRouteWithChildren = AppEnviosRoute._addFileChildren(
  AppEnviosRouteChildren,
)

interface AppPessoasRouteChildren {
  AppPessoasIdRoute: typeof AppPessoasIdRoute
}

const AppPessoasRouteChildren: AppPessoasRouteChildren = {
  AppPessoasIdRoute: AppPessoasIdRoute,
}

const AppPessoasRouteWithChildren = AppPessoasRoute._addFileChildren(
  AppPessoasRouteChildren,
)

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEnviosRoute: typeof AppEnviosRouteWithChildren
  AppEstatisticasRoute: typeof AppEstatisticasRoute
  AppGruposRoute: typeof AppGruposRoute
  AppMentoresRoute: typeof AppMentoresRoute
  AppPessoasRoute: typeof AppPessoasRouteWithChildren
  AppTestesRoute: typeof AppTestesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEnviosRoute: AppEnviosRouteWithChildren,
  AppEstatisticasRoute: AppEstatisticasRoute,
  AppGruposRoute: AppGruposRoute,
  AppMentoresRoute: AppMentoresRoute,
  AppPessoasRoute: AppPessoasRouteWithChildren,
  AppTestesRoute: AppTestesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
