/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CriarSenhaRouteImport } from './routes/criar-senha'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'
import { Route as AppColaboradoresRouteImport } from './routes/_app.colaboradores'
import { Route as AppComunidadesRouteImport } from './routes/_app.comunidades'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppEnviosRouteImport } from './routes/_app.envios'
import { Route as AppGruposRouteImport } from './routes/_app.grupos'
import { Route as AppMentoresRouteImport } from './routes/_app.mentores'
import { Route as AppMentoriasRouteImport } from './routes/_app.mentorias'
import { Route as AppPessoasRouteImport } from './routes/_app.pessoas'
import { Route as AppRespostasRouteImport } from './routes/_app.respostas'
import { Route as AppTestesRouteImport } from './routes/_app.testes'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as AlunoAgendaRouteImport } from './routes/aluno.agenda'
import { Route as AlunoComunidadeRouteImport } from './routes/aluno.comunidade'
import { Route as AlunoCriarSenhaRouteImport } from './routes/aluno.criar-senha'
import { Route as AlunoGruposRouteImport } from './routes/aluno.grupos'
import { Route as AlunoMentoriasRouteImport } from './routes/aluno.mentorias'
import { Route as AlunoPerfilRouteImport } from './routes/aluno.perfil'
import { Route as AlunoRankingRouteImport } from './routes/aluno.ranking'
import { Route as ApiManifestRouteImport } from './routes/api.manifest'
import { Route as ApiMarcaRouteImport } from './routes/api.marca'
import { Route as BateriaAssessmentIdRouteImport } from './routes/bateria.$assessmentId'
import { Route as CheckinAulaIdRouteImport } from './routes/checkin.$aulaId'
import { Route as ConviteEquipeTokenRouteImport } from './routes/convite-equipe.$token'
import { Route as ConviteLinkIdRouteImport } from './routes/convite.$linkId'
import { Route as RelatorioBateriaAssessmentIdRouteImport } from './routes/relatorio-bateria.$assessmentId'
import { Route as RelatorioResponseIdRouteImport } from './routes/relatorio.$responseId'
import { Route as ResponderResponseIdRouteImport } from './routes/responder.$responseId'
import { Route as SessaoIdRouteImport } from './routes/sessao.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AppClassroomIndexRouteImport } from './routes/_app.classroom.index'
import { Route as AppClassroomTreinamentoIdRouteImport } from './routes/_app.classroom.$treinamentoId'
import { Route as AppEducacaoIndexRouteImport } from './routes/_app.educacao.index'
import { Route as AppEducacaoTrackIdRouteImport } from './routes/_app.educacao.$trackId'
import { Route as AppEnviosIndexRouteImport } from './routes/_app.envios.index'
import { Route as AppEnviosNovoRouteImport } from './routes/_app.envios.novo'
import { Route as AppGruposIndexRouteImport } from './routes/_app.grupos.index'
import { Route as AppGruposIdRouteImport } from './routes/_app.grupos.$id'
import { Route as AppMentoriasIndexRouteImport } from './routes/_app.mentorias.index'
import { Route as AppMentoriasIdRouteImport } from './routes/_app.mentorias.$id'
import { Route as AppMentoriasAgendamentoRouteImport } from './routes/_app.mentorias.agendamento'
import { Route as AppPessoasIndexRouteImport } from './routes/_app.pessoas.index'
import { Route as AppPessoasIdRouteImport } from './routes/_app.pessoas.$id'
import { Route as AppRespostasIndexRouteImport } from './routes/_app.respostas.index'
import { Route as AppTestesIndexRouteImport } from './routes/_app.testes.index'
import { Route as AlunoClassroomIndexRouteImport } from './routes/aluno.classroom.index'
import { Route as AlunoClassroomTreinamentoIdRouteImport } from './routes/aluno.classroom.$treinamentoId'
import { Route as AlunoEducacaoIndexRouteImport } from './routes/aluno.educacao.index'
import { Route as AlunoEducacaoTrackIdRouteImport } from './routes/aluno.educacao.$trackId'
import { Route as ApiCronLembretesRouteImport } from './routes/api.cron.lembretes'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api.google.callback'
import { Route as ApiIconeTamanhoRouteImport } from './routes/api.icone.$tamanho'
import { Route as ApiMentorFotoSlugRouteImport } from './routes/api.mentor-foto.$slug'
import { Route as AppTestesVersionIdEditarRouteImport } from './routes/_app.testes.$versionId.editar'
import { Route as AppTestesVersionIdRespostasRouteImport } from './routes/_app.testes.$versionId.respostas'
import { Route as ApiPublicActionPlanIdRouteImport } from './routes/api.public.action-plan.$id'
import { Route as ApiPublicAssessmentIdRouteImport } from './routes/api.public.assessment.$id'
import { Route as ApiPublicCheckinAulaIdRouteImport } from './routes/api.public.checkin.$aulaId'
import { Route as ApiPublicInviteIdRouteImport } from './routes/api.public.invite.$id'
import { Route as ApiPublicReportBateriaIdRouteImport } from './routes/api.public.report-bateria.$id'
import { Route as ApiPublicReportIdRouteImport } from './routes/api.public.report.$id'
import { Route as ApiPublicResponseIdRouteImport } from './routes/api.public.response.$id'
import { Route as AppTestesVersionIdPdfResponseIdRouteImport } from './routes/_app.testes.$versionId.pdf.$responseId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarSenhaRoute = CriarSenhaRouteImport.update({
  id: '/criar-senha',
  path: '/criar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppColaboradoresRoute = AppColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => AppRoute,
} as any)
const AppComunidadesRoute = AppComunidadesRouteImport.update({
  id: '/comunidades',
  path: '/comunidades',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEnviosRoute = AppEnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => AppRoute,
} as any)
const AppGruposRoute = AppGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AppRoute,
} as any)
const AppMentoresRoute = AppMentoresRouteImport.update({
  id: '/mentores',
  path: '/mentores',
  getParentRoute: () => AppRoute,
} as any)
const AppMentoriasRoute = AppMentoriasRouteImport.update({
  id: '/mentorias',
  path: '/mentorias',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasRoute = AppPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AppRoute,
} as any)
const AppRespostasRoute = AppRespostasRouteImport.update({
  id: '/respostas',
  path: '/respostas',
  getParentRoute: () => AppRoute,
} as any)
const AppTestesRoute = AppTestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => AppRoute,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoAgendaRoute = AlunoAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoComunidadeRoute = AlunoComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoCriarSenhaRoute = AlunoCriarSenhaRouteImport.update({
  id: '/criar-senha',
  path: '/criar-senha',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoGruposRoute = AlunoGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoMentoriasRoute = AlunoMentoriasRouteImport.update({
  id: '/mentorias',
  path: '/mentorias',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoPerfilRoute = AlunoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoRankingRoute = AlunoRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AlunoRoute,
} as any)
const ApiManifestRoute = ApiManifestRouteImport.update({
  id: '/api/manifest',
  path: '/api/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarcaRoute = ApiMarcaRouteImport.update({
  id: '/api/marca',
  path: '/api/marca',
  getParentRoute: () => rootRouteImport,
} as any)
const BateriaAssessmentIdRoute = BateriaAssessmentIdRouteImport.update({
  id: '/bateria/$assessmentId',
  path: '/bateria/$assessmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinAulaIdRoute = CheckinAulaIdRouteImport.update({
  id: '/checkin/$aulaId',
  path: '/checkin/$aulaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteEquipeTokenRoute = ConviteEquipeTokenRouteImport.update({
  id: '/convite-equipe/$token',
  path: '/convite-equipe/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteLinkIdRoute = ConviteLinkIdRouteImport.update({
  id: '/convite/$linkId',
  path: '/convite/$linkId',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioBateriaAssessmentIdRoute =
  RelatorioBateriaAssessmentIdRouteImport.update({
    id: '/relatorio-bateria/$assessmentId',
    path: '/relatorio-bateria/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RelatorioResponseIdRoute = RelatorioResponseIdRouteImport.update({
  id: '/relatorio/$responseId',
  path: '/relatorio/$responseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderResponseIdRoute = ResponderResponseIdRouteImport.update({
  id: '/responder/$responseId',
  path: '/responder/$responseId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessaoIdRoute = SessaoIdRouteImport.update({
  id: '/sessao/$id',
  path: '/sessao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppClassroomIndexRoute = AppClassroomIndexRouteImport.update({
  id: '/classroom/',
  path: '/classroom/',
  getParentRoute: () => AppRoute,
} as any)
const AppClassroomTreinamentoIdRoute =
  AppClassroomTreinamentoIdRouteImport.update({
    id: '/classroom/$treinamentoId',
    path: '/classroom/$treinamentoId',
    getParentRoute: () => AppRoute,
  } as any)
const AppEducacaoIndexRoute = AppEducacaoIndexRouteImport.update({
  id: '/educacao/',
  path: '/educacao/',
  getParentRoute: () => AppRoute,
} as any)
const AppEducacaoTrackIdRoute = AppEducacaoTrackIdRouteImport.update({
  id: '/educacao/$trackId',
  path: '/educacao/$trackId',
  getParentRoute: () => AppRoute,
} as any)
const AppEnviosIndexRoute = AppEnviosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEnviosRoute,
} as any)
const AppEnviosNovoRoute = AppEnviosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppEnviosRoute,
} as any)
const AppGruposIndexRoute = AppGruposIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGruposRoute,
} as any)
const AppGruposIdRoute = AppGruposIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppGruposRoute,
} as any)
const AppMentoriasIndexRoute = AppMentoriasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMentoriasRoute,
} as any)
const AppMentoriasIdRoute = AppMentoriasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMentoriasRoute,
} as any)
const AppMentoriasAgendamentoRoute = AppMentoriasAgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => AppMentoriasRoute,
} as any)
const AppPessoasIndexRoute = AppPessoasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPessoasRoute,
} as any)
const AppPessoasIdRoute = AppPessoasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPessoasRoute,
} as any)
const AppRespostasIndexRoute = AppRespostasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRespostasRoute,
} as any)
const AppTestesIndexRoute = AppTestesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTestesRoute,
} as any)
const AlunoClassroomIndexRoute = AlunoClassroomIndexRouteImport.update({
  id: '/classroom/',
  path: '/classroom/',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoClassroomTreinamentoIdRoute =
  AlunoClassroomTreinamentoIdRouteImport.update({
    id: '/classroom/$treinamentoId',
    path: '/classroom/$treinamentoId',
    getParentRoute: () => AlunoRoute,
  } as any)
const AlunoEducacaoIndexRoute = AlunoEducacaoIndexRouteImport.update({
  id: '/educacao/',
  path: '/educacao/',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoEducacaoTrackIdRoute = AlunoEducacaoTrackIdRouteImport.update({
  id: '/educacao/$trackId',
  path: '/educacao/$trackId',
  getParentRoute: () => AlunoRoute,
} as any)
const ApiCronLembretesRoute = ApiCronLembretesRouteImport.update({
  id: '/api/cron/lembretes',
  path: '/api/cron/lembretes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIconeTamanhoRoute = ApiIconeTamanhoRouteImport.update({
  id: '/api/icone/$tamanho',
  path: '/api/icone/$tamanho',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorFotoSlugRoute = ApiMentorFotoSlugRouteImport.update({
  id: '/api/mentor-foto/$slug',
  path: '/api/mentor-foto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTestesVersionIdEditarRoute =
  AppTestesVersionIdEditarRouteImport.update({
    id: '/$versionId/editar',
    path: '/$versionId/editar',
    getParentRoute: () => AppTestesRoute,
  } as any)
const AppTestesVersionIdRespostasRoute =
  AppTestesVersionIdRespostasRouteImport.update({
    id: '/$versionId/respostas',
    path: '/$versionId/respostas',
    getParentRoute: () => AppTestesRoute,
  } as any)
const ApiPublicActionPlanIdRoute = ApiPublicActionPlanIdRouteImport.update({
  id: '/api/public/action-plan/$id',
  path: '/api/public/action-plan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAssessmentIdRoute = ApiPublicAssessmentIdRouteImport.update({
  id: '/api/public/assessment/$id',
  path: '/api/public/assessment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckinAulaIdRoute = ApiPublicCheckinAulaIdRouteImport.update({
  id: '/api/public/checkin/$aulaId',
  path: '/api/public/checkin/$aulaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInviteIdRoute = ApiPublicInviteIdRouteImport.update({
  id: '/api/public/invite/$id',
  path: '/api/public/invite/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReportBateriaIdRoute =
  ApiPublicReportBateriaIdRouteImport.update({
    id: '/api/public/report-bateria/$id',
    path: '/api/public/report-bateria/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicReportIdRoute = ApiPublicReportIdRouteImport.update({
  id: '/api/public/report/$id',
  path: '/api/public/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResponseIdRoute = ApiPublicResponseIdRouteImport.update({
  id: '/api/public/response/$id',
  path: '/api/public/response/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTestesVersionIdPdfResponseIdRoute =
  AppTestesVersionIdPdfResponseIdRouteImport.update({
    id: '/$versionId/pdf/$responseId',
    path: '/$versionId/pdf/$responseId',
    getParentRoute: () => AppTestesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/auth': typeof AuthRoute
  '/criar-senha': typeof CriarSenhaRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agenda': typeof AppAgendaRoute
  '/colaboradores': typeof AppColaboradoresRoute
  '/comunidades': typeof AppComunidadesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/envios': typeof AppEnviosRouteWithChildren
  '/grupos': typeof AppGruposRouteWithChildren
  '/mentores': typeof AppMentoresRoute
  '/mentorias': typeof AppMentoriasRouteWithChildren
  '/pessoas': typeof AppPessoasRouteWithChildren
  '/respostas': typeof AppRespostasRouteWithChildren
  '/testes': typeof AppTestesRouteWithChildren
  '/agendar/$slug': typeof AgendarSlugRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/comunidade': typeof AlunoComunidadeRoute
  '/aluno/criar-senha': typeof AlunoCriarSenhaRoute
  '/aluno/grupos': typeof AlunoGruposRoute
  '/aluno/mentorias': typeof AlunoMentoriasRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/ranking': typeof AlunoRankingRoute
  '/api/manifest': typeof ApiManifestRoute
  '/api/marca': typeof ApiMarcaRoute
  '/bateria/$assessmentId': typeof BateriaAssessmentIdRoute
  '/checkin/$aulaId': typeof CheckinAulaIdRoute
  '/convite-equipe/$token': typeof ConviteEquipeTokenRoute
  '/convite/$linkId': typeof ConviteLinkIdRoute
  '/relatorio-bateria/$assessmentId': typeof RelatorioBateriaAssessmentIdRoute
  '/relatorio/$responseId': typeof RelatorioResponseIdRoute
  '/responder/$responseId': typeof ResponderResponseIdRoute
  '/sessao/$id': typeof SessaoIdRoute
  '/aluno/': typeof AlunoIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/classroom/$treinamentoId': typeof AppClassroomTreinamentoIdRoute
  '/educacao/$trackId': typeof AppEducacaoTrackIdRoute
  '/envios/novo': typeof AppEnviosNovoRoute
  '/grupos/$id': typeof AppGruposIdRoute
  '/mentorias/$id': typeof AppMentoriasIdRoute
  '/mentorias/agendamento': typeof AppMentoriasAgendamentoRoute
  '/pessoas/$id': typeof AppPessoasIdRoute
  '/aluno/classroom/$treinamentoId': typeof AlunoClassroomTreinamentoIdRoute
  '/aluno/educacao/$trackId': typeof AlunoEducacaoTrackIdRoute
  '/api/cron/lembretes': typeof ApiCronLembretesRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/icone/$tamanho': typeof ApiIconeTamanhoRoute
  '/api/mentor-foto/$slug': typeof ApiMentorFotoSlugRoute
  '/classroom/': typeof AppClassroomIndexRoute
  '/educacao/': typeof AppEducacaoIndexRoute
  '/envios/': typeof AppEnviosIndexRoute
  '/grupos/': typeof AppGruposIndexRoute
  '/mentorias/': typeof AppMentoriasIndexRoute
  '/pessoas/': typeof AppPessoasIndexRoute
  '/respostas/': typeof AppRespostasIndexRoute
  '/testes/': typeof AppTestesIndexRoute
  '/aluno/classroom/': typeof AlunoClassroomIndexRoute
  '/aluno/educacao/': typeof AlunoEducacaoIndexRoute
  '/testes/$versionId/editar': typeof AppTestesVersionIdEditarRoute
  '/testes/$versionId/respostas': typeof AppTestesVersionIdRespostasRoute
  '/api/public/action-plan/$id': typeof ApiPublicActionPlanIdRoute
  '/api/public/assessment/$id': typeof ApiPublicAssessmentIdRoute
  '/api/public/checkin/$aulaId': typeof ApiPublicCheckinAulaIdRoute
  '/api/public/invite/$id': typeof ApiPublicInviteIdRoute
  '/api/public/report-bateria/$id': typeof ApiPublicReportBateriaIdRoute
  '/api/public/report/$id': typeof ApiPublicReportIdRoute
  '/api/public/response/$id': typeof ApiPublicResponseIdRoute
  '/testes/$versionId/pdf/$responseId': typeof AppTestesVersionIdPdfResponseIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/criar-senha': typeof CriarSenhaRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agenda': typeof AppAgendaRoute
  '/colaboradores': typeof AppColaboradoresRoute
  '/comunidades': typeof AppComunidadesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/mentores': typeof AppMentoresRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/comunidade': typeof AlunoComunidadeRoute
  '/aluno/criar-senha': typeof AlunoCriarSenhaRoute
  '/aluno/grupos': typeof AlunoGruposRoute
  '/aluno/mentorias': typeof AlunoMentoriasRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/ranking': typeof AlunoRankingRoute
  '/api/manifest': typeof ApiManifestRoute
  '/api/marca': typeof ApiMarcaRoute
  '/bateria/$assessmentId': typeof BateriaAssessmentIdRoute
  '/checkin/$aulaId': typeof CheckinAulaIdRoute
  '/convite-equipe/$token': typeof ConviteEquipeTokenRoute
  '/convite/$linkId': typeof ConviteLinkIdRoute
  '/relatorio-bateria/$assessmentId': typeof RelatorioBateriaAssessmentIdRoute
  '/relatorio/$responseId': typeof RelatorioResponseIdRoute
  '/responder/$responseId': typeof ResponderResponseIdRoute
  '/sessao/$id': typeof SessaoIdRoute
  '/': typeof AppIndexRoute
  '/aluno': typeof AlunoIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/classroom/$treinamentoId': typeof AppClassroomTreinamentoIdRoute
  '/educacao/$trackId': typeof AppEducacaoTrackIdRoute
  '/envios/novo': typeof AppEnviosNovoRoute
  '/grupos/$id': typeof AppGruposIdRoute
  '/mentorias/$id': typeof AppMentoriasIdRoute
  '/mentorias/agendamento': typeof AppMentoriasAgendamentoRoute
  '/pessoas/$id': typeof AppPessoasIdRoute
  '/aluno/classroom/$treinamentoId': typeof AlunoClassroomTreinamentoIdRoute
  '/aluno/educacao/$trackId': typeof AlunoEducacaoTrackIdRoute
  '/api/cron/lembretes': typeof ApiCronLembretesRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/icone/$tamanho': typeof ApiIconeTamanhoRoute
  '/api/mentor-foto/$slug': typeof ApiMentorFotoSlugRoute
  '/classroom': typeof AppClassroomIndexRoute
  '/educacao': typeof AppEducacaoIndexRoute
  '/envios': typeof AppEnviosIndexRoute
  '/grupos': typeof AppGruposIndexRoute
  '/mentorias': typeof AppMentoriasIndexRoute
  '/pessoas': typeof AppPessoasIndexRoute
  '/respostas': typeof AppRespostasIndexRoute
  '/testes': typeof AppTestesIndexRoute
  '/aluno/classroom': typeof AlunoClassroomIndexRoute
  '/aluno/educacao': typeof AlunoEducacaoIndexRoute
  '/testes/$versionId/editar': typeof AppTestesVersionIdEditarRoute
  '/testes/$versionId/respostas': typeof AppTestesVersionIdRespostasRoute
  '/api/public/action-plan/$id': typeof ApiPublicActionPlanIdRoute
  '/api/public/assessment/$id': typeof ApiPublicAssessmentIdRoute
  '/api/public/checkin/$aulaId': typeof ApiPublicCheckinAulaIdRoute
  '/api/public/invite/$id': typeof ApiPublicInviteIdRoute
  '/api/public/report-bateria/$id': typeof ApiPublicReportBateriaIdRoute
  '/api/public/report/$id': typeof ApiPublicReportIdRoute
  '/api/public/response/$id': typeof ApiPublicResponseIdRoute
  '/testes/$versionId/pdf/$responseId': typeof AppTestesVersionIdPdfResponseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/auth': typeof AuthRoute
  '/criar-senha': typeof CriarSenhaRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/colaboradores': typeof AppColaboradoresRoute
  '/_app/comunidades': typeof AppComunidadesRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/envios': typeof AppEnviosRouteWithChildren
  '/_app/grupos': typeof AppGruposRouteWithChildren
  '/_app/mentores': typeof AppMentoresRoute
  '/_app/mentorias': typeof AppMentoriasRouteWithChildren
  '/_app/pessoas': typeof AppPessoasRouteWithChildren
  '/_app/respostas': typeof AppRespostasRouteWithChildren
  '/_app/testes': typeof AppTestesRouteWithChildren
  '/agendar/$slug': typeof AgendarSlugRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/comunidade': typeof AlunoComunidadeRoute
  '/aluno/criar-senha': typeof AlunoCriarSenhaRoute
  '/aluno/grupos': typeof AlunoGruposRoute
  '/aluno/mentorias': typeof AlunoMentoriasRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/ranking': typeof AlunoRankingRoute
  '/api/manifest': typeof ApiManifestRoute
  '/api/marca': typeof ApiMarcaRoute
  '/bateria/$assessmentId': typeof BateriaAssessmentIdRoute
  '/checkin/$aulaId': typeof CheckinAulaIdRoute
  '/convite-equipe/$token': typeof ConviteEquipeTokenRoute
  '/convite/$linkId': typeof ConviteLinkIdRoute
  '/relatorio-bateria/$assessmentId': typeof RelatorioBateriaAssessmentIdRoute
  '/relatorio/$responseId': typeof RelatorioResponseIdRoute
  '/responder/$responseId': typeof ResponderResponseIdRoute
  '/sessao/$id': typeof SessaoIdRoute
  '/_app/': typeof AppIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/classroom/$treinamentoId': typeof AppClassroomTreinamentoIdRoute
  '/_app/educacao/$trackId': typeof AppEducacaoTrackIdRoute
  '/_app/envios/novo': typeof AppEnviosNovoRoute
  '/_app/grupos/$id': typeof AppGruposIdRoute
  '/_app/mentorias/$id': typeof AppMentoriasIdRoute
  '/_app/mentorias/agendamento': typeof AppMentoriasAgendamentoRoute
  '/_app/pessoas/$id': typeof AppPessoasIdRoute
  '/aluno/classroom/$treinamentoId': typeof AlunoClassroomTreinamentoIdRoute
  '/aluno/educacao/$trackId': typeof AlunoEducacaoTrackIdRoute
  '/api/cron/lembretes': typeof ApiCronLembretesRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/icone/$tamanho': typeof ApiIconeTamanhoRoute
  '/api/mentor-foto/$slug': typeof ApiMentorFotoSlugRoute
  '/_app/classroom/': typeof AppClassroomIndexRoute
  '/_app/educacao/': typeof AppEducacaoIndexRoute
  '/_app/envios/': typeof AppEnviosIndexRoute
  '/_app/grupos/': typeof AppGruposIndexRoute
  '/_app/mentorias/': typeof AppMentoriasIndexRoute
  '/_app/pessoas/': typeof AppPessoasIndexRoute
  '/_app/respostas/': typeof AppRespostasIndexRoute
  '/_app/testes/': typeof AppTestesIndexRoute
  '/aluno/classroom/': typeof AlunoClassroomIndexRoute
  '/aluno/educacao/': typeof AlunoEducacaoIndexRoute
  '/_app/testes/$versionId/editar': typeof AppTestesVersionIdEditarRoute
  '/_app/testes/$versionId/respostas': typeof AppTestesVersionIdRespostasRoute
  '/api/public/action-plan/$id': typeof ApiPublicActionPlanIdRoute
  '/api/public/assessment/$id': typeof ApiPublicAssessmentIdRoute
  '/api/public/checkin/$aulaId': typeof ApiPublicCheckinAulaIdRoute
  '/api/public/invite/$id': typeof ApiPublicInviteIdRoute
  '/api/public/report-bateria/$id': typeof ApiPublicReportBateriaIdRoute
  '/api/public/report/$id': typeof ApiPublicReportIdRoute
  '/api/public/response/$id': typeof ApiPublicResponseIdRoute
  '/_app/testes/$versionId/pdf/$responseId': typeof AppTestesVersionIdPdfResponseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aluno'
    | '/auth'
    | '/criar-senha'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agenda'
    | '/colaboradores'
    | '/comunidades'
    | '/configuracoes'
    | '/envios'
    | '/grupos'
    | '/mentores'
    | '/mentorias'
    | '/pessoas'
    | '/respostas'
    | '/testes'
    | '/agendar/$slug'
    | '/aluno/agenda'
    | '/aluno/comunidade'
    | '/aluno/criar-senha'
    | '/aluno/grupos'
    | '/aluno/mentorias'
    | '/aluno/perfil'
    | '/aluno/ranking'
    | '/api/manifest'
    | '/api/marca'
    | '/bateria/$assessmentId'
    | '/checkin/$aulaId'
    | '/convite-equipe/$token'
    | '/convite/$linkId'
    | '/relatorio-bateria/$assessmentId'
    | '/relatorio/$responseId'
    | '/responder/$responseId'
    | '/sessao/$id'
    | '/aluno/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/classroom/$treinamentoId'
    | '/educacao/$trackId'
    | '/envios/novo'
    | '/grupos/$id'
    | '/mentorias/$id'
    | '/mentorias/agendamento'
    | '/pessoas/$id'
    | '/aluno/classroom/$treinamentoId'
    | '/aluno/educacao/$trackId'
    | '/api/cron/lembretes'
    | '/api/google/callback'
    | '/api/icone/$tamanho'
    | '/api/mentor-foto/$slug'
    | '/classroom/'
    | '/educacao/'
    | '/envios/'
    | '/grupos/'
    | '/mentorias/'
    | '/pessoas/'
    | '/respostas/'
    | '/testes/'
    | '/aluno/classroom/'
    | '/aluno/educacao/'
    | '/testes/$versionId/editar'
    | '/testes/$versionId/respostas'
    | '/api/public/action-plan/$id'
    | '/api/public/assessment/$id'
    | '/api/public/checkin/$aulaId'
    | '/api/public/invite/$id'
    | '/api/public/report-bateria/$id'
    | '/api/public/report/$id'
    | '/api/public/response/$id'
    | '/testes/$versionId/pdf/$responseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/criar-senha'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agenda'
    | '/colaboradores'
    | '/comunidades'
    | '/configuracoes'
    | '/mentores'
    | '/agendar/$slug'
    | '/aluno/agenda'
    | '/aluno/comunidade'
    | '/aluno/criar-senha'
    | '/aluno/grupos'
    | '/aluno/mentorias'
    | '/aluno/perfil'
    | '/aluno/ranking'
    | '/api/manifest'
    | '/api/marca'
    | '/bateria/$assessmentId'
    | '/checkin/$aulaId'
    | '/convite-equipe/$token'
    | '/convite/$linkId'
    | '/relatorio-bateria/$assessmentId'
    | '/relatorio/$responseId'
    | '/responder/$responseId'
    | '/sessao/$id'
    | '/'
    | '/aluno'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/classroom/$treinamentoId'
    | '/educacao/$trackId'
    | '/envios/novo'
    | '/grupos/$id'
    | '/mentorias/$id'
    | '/mentorias/agendamento'
    | '/pessoas/$id'
    | '/aluno/classroom/$treinamentoId'
    | '/aluno/educacao/$trackId'
    | '/api/cron/lembretes'
    | '/api/google/callback'
    | '/api/icone/$tamanho'
    | '/api/mentor-foto/$slug'
    | '/classroom'
    | '/educacao'
    | '/envios'
    | '/grupos'
    | '/mentorias'
    | '/pessoas'
    | '/respostas'
    | '/testes'
    | '/aluno/classroom'
    | '/aluno/educacao'
    | '/testes/$versionId/editar'
    | '/testes/$versionId/respostas'
    | '/api/public/action-plan/$id'
    | '/api/public/assessment/$id'
    | '/api/public/checkin/$aulaId'
    | '/api/public/invite/$id'
    | '/api/public/report-bateria/$id'
    | '/api/public/report/$id'
    | '/api/public/response/$id'
    | '/testes/$versionId/pdf/$responseId'
  id:
    | '__root__'
    | '/_app'
    | '/aluno'
    | '/auth'
    | '/criar-senha'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/agenda'
    | '/_app/colaboradores'
    | '/_app/comunidades'
    | '/_app/configuracoes'
    | '/_app/envios'
    | '/_app/grupos'
    | '/_app/mentores'
    | '/_app/mentorias'
    | '/_app/pessoas'
    | '/_app/respostas'
    | '/_app/testes'
    | '/agendar/$slug'
    | '/aluno/agenda'
    | '/aluno/comunidade'
    | '/aluno/criar-senha'
    | '/aluno/grupos'
    | '/aluno/mentorias'
    | '/aluno/perfil'
    | '/aluno/ranking'
    | '/api/manifest'
    | '/api/marca'
    | '/bateria/$assessmentId'
    | '/checkin/$aulaId'
    | '/convite-equipe/$token'
    | '/convite/$linkId'
    | '/relatorio-bateria/$assessmentId'
    | '/relatorio/$responseId'
    | '/responder/$responseId'
    | '/sessao/$id'
    | '/_app/'
    | '/aluno/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/classroom/$treinamentoId'
    | '/_app/educacao/$trackId'
    | '/_app/envios/novo'
    | '/_app/grupos/$id'
    | '/_app/mentorias/$id'
    | '/_app/mentorias/agendamento'
    | '/_app/pessoas/$id'
    | '/aluno/classroom/$treinamentoId'
    | '/aluno/educacao/$trackId'
    | '/api/cron/lembretes'
    | '/api/google/callback'
    | '/api/icone/$tamanho'
    | '/api/mentor-foto/$slug'
    | '/_app/classroom/'
    | '/_app/educacao/'
    | '/_app/envios/'
    | '/_app/grupos/'
    | '/_app/mentorias/'
    | '/_app/pessoas/'
    | '/_app/respostas/'
    | '/_app/testes/'
    | '/aluno/classroom/'
    | '/aluno/educacao/'
    | '/_app/testes/$versionId/editar'
    | '/_app/testes/$versionId/respostas'
    | '/api/public/action-plan/$id'
    | '/api/public/assessment/$id'
    | '/api/public/checkin/$aulaId'
    | '/api/public/invite/$id'
    | '/api/public/report-bateria/$id'
    | '/api/public/report/$id'
    | '/api/public/response/$id'
    | '/_app/testes/$versionId/pdf/$responseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AlunoRoute: typeof AlunoRouteWithChildren
  AuthRoute: typeof AuthRoute
  CriarSenhaRoute: typeof CriarSenhaRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AgendarSlugRoute: typeof AgendarSlugRoute
  ApiManifestRoute: typeof ApiManifestRoute
  ApiMarcaRoute: typeof ApiMarcaRoute
  BateriaAssessmentIdRoute: typeof BateriaAssessmentIdRoute
  CheckinAulaIdRoute: typeof CheckinAulaIdRoute
  ConviteEquipeTokenRoute: typeof ConviteEquipeTokenRoute
  ConviteLinkIdRoute: typeof ConviteLinkIdRoute
  RelatorioBateriaAssessmentIdRoute: typeof RelatorioBateriaAssessmentIdRoute
  RelatorioResponseIdRoute: typeof RelatorioResponseIdRoute
  ResponderResponseIdRoute: typeof ResponderResponseIdRoute
  SessaoIdRoute: typeof SessaoIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiCronLembretesRoute: typeof ApiCronLembretesRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiIconeTamanhoRoute: typeof ApiIconeTamanhoRoute
  ApiMentorFotoSlugRoute: typeof ApiMentorFotoSlugRoute
  ApiPublicActionPlanIdRoute: typeof ApiPublicActionPlanIdRoute
  ApiPublicAssessmentIdRoute: typeof ApiPublicAssessmentIdRoute
  ApiPublicCheckinAulaIdRoute: typeof ApiPublicCheckinAulaIdRoute
  ApiPublicInviteIdRoute: typeof ApiPublicInviteIdRoute
  ApiPublicReportBateriaIdRoute: typeof ApiPublicReportBateriaIdRoute
  ApiPublicReportIdRoute: typeof ApiPublicReportIdRoute
  ApiPublicResponseIdRoute: typeof ApiPublicResponseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-senha': {
      id: '/criar-senha'
      path: '/criar-senha'
      fullPath: '/criar-senha'
      preLoaderRoute: typeof CriarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colaboradores': {
      id: '/_app/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AppColaboradoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comunidades': {
      id: '/_app/comunidades'
      path: '/comunidades'
      fullPath: '/comunidades'
      preLoaderRoute: typeof AppComunidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/envios': {
      id: '/_app/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof AppEnviosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grupos': {
      id: '/_app/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AppGruposRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mentores': {
      id: '/_app/mentores'
      path: '/mentores'
      fullPath: '/mentores'
      preLoaderRoute: typeof AppMentoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mentorias': {
      id: '/_app/mentorias'
      path: '/mentorias'
      fullPath: '/mentorias'
      preLoaderRoute: typeof AppMentoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pessoas': {
      id: '/_app/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof AppPessoasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/respostas': {
      id: '/_app/respostas'
      path: '/respostas'
      fullPath: '/respostas'
      preLoaderRoute: typeof AppRespostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/testes': {
      id: '/_app/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof AppTestesRouteImport
      parentRoute: typeof AppRoute
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/agenda': {
      id: '/aluno/agenda'
      path: '/agenda'
      fullPath: '/aluno/agenda'
      preLoaderRoute: typeof AlunoAgendaRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/comunidade': {
      id: '/aluno/comunidade'
      path: '/comunidade'
      fullPath: '/aluno/comunidade'
      preLoaderRoute: typeof AlunoComunidadeRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/criar-senha': {
      id: '/aluno/criar-senha'
      path: '/criar-senha'
      fullPath: '/aluno/criar-senha'
      preLoaderRoute: typeof AlunoCriarSenhaRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/grupos': {
      id: '/aluno/grupos'
      path: '/grupos'
      fullPath: '/aluno/grupos'
      preLoaderRoute: typeof AlunoGruposRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/mentorias': {
      id: '/aluno/mentorias'
      path: '/mentorias'
      fullPath: '/aluno/mentorias'
      preLoaderRoute: typeof AlunoMentoriasRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/perfil': {
      id: '/aluno/perfil'
      path: '/perfil'
      fullPath: '/aluno/perfil'
      preLoaderRoute: typeof AlunoPerfilRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/ranking': {
      id: '/aluno/ranking'
      path: '/ranking'
      fullPath: '/aluno/ranking'
      preLoaderRoute: typeof AlunoRankingRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/api/manifest': {
      id: '/api/manifest'
      path: '/api/manifest'
      fullPath: '/api/manifest'
      preLoaderRoute: typeof ApiManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marca': {
      id: '/api/marca'
      path: '/api/marca'
      fullPath: '/api/marca'
      preLoaderRoute: typeof ApiMarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bateria/$assessmentId': {
      id: '/bateria/$assessmentId'
      path: '/bateria/$assessmentId'
      fullPath: '/bateria/$assessmentId'
      preLoaderRoute: typeof BateriaAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$aulaId': {
      id: '/checkin/$aulaId'
      path: '/checkin/$aulaId'
      fullPath: '/checkin/$aulaId'
      preLoaderRoute: typeof CheckinAulaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite-equipe/$token': {
      id: '/convite-equipe/$token'
      path: '/convite-equipe/$token'
      fullPath: '/convite-equipe/$token'
      preLoaderRoute: typeof ConviteEquipeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$linkId': {
      id: '/convite/$linkId'
      path: '/convite/$linkId'
      fullPath: '/convite/$linkId'
      preLoaderRoute: typeof ConviteLinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-bateria/$assessmentId': {
      id: '/relatorio-bateria/$assessmentId'
      path: '/relatorio-bateria/$assessmentId'
      fullPath: '/relatorio-bateria/$assessmentId'
      preLoaderRoute: typeof RelatorioBateriaAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio/$responseId': {
      id: '/relatorio/$responseId'
      path: '/relatorio/$responseId'
      fullPath: '/relatorio/$responseId'
      preLoaderRoute: typeof RelatorioResponseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder/$responseId': {
      id: '/responder/$responseId'
      path: '/responder/$responseId'
      fullPath: '/responder/$responseId'
      preLoaderRoute: typeof ResponderResponseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessao/$id': {
      id: '/sessao/$id'
      path: '/sessao/$id'
      fullPath: '/sessao/$id'
      preLoaderRoute: typeof SessaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/classroom/': {
      id: '/_app/classroom/'
      path: '/classroom'
      fullPath: '/classroom/'
      preLoaderRoute: typeof AppClassroomIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classroom/$treinamentoId': {
      id: '/_app/classroom/$treinamentoId'
      path: '/classroom/$treinamentoId'
      fullPath: '/classroom/$treinamentoId'
      preLoaderRoute: typeof AppClassroomTreinamentoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/educacao/': {
      id: '/_app/educacao/'
      path: '/educacao'
      fullPath: '/educacao/'
      preLoaderRoute: typeof AppEducacaoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/educacao/$trackId': {
      id: '/_app/educacao/$trackId'
      path: '/educacao/$trackId'
      fullPath: '/educacao/$trackId'
      preLoaderRoute: typeof AppEducacaoTrackIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/envios/': {
      id: '/_app/envios/'
      path: '/'
      fullPath: '/envios/'
      preLoaderRoute: typeof AppEnviosIndexRouteImport
      parentRoute: typeof AppEnviosRoute
    }
    '/_app/envios/novo': {
      id: '/_app/envios/novo'
      path: '/novo'
      fullPath: '/envios/novo'
      preLoaderRoute: typeof AppEnviosNovoRouteImport
      parentRoute: typeof AppEnviosRoute
    }
    '/_app/grupos/': {
      id: '/_app/grupos/'
      path: '/'
      fullPath: '/grupos/'
      preLoaderRoute: typeof AppGruposIndexRouteImport
      parentRoute: typeof AppGruposRoute
    }
    '/_app/grupos/$id': {
      id: '/_app/grupos/$id'
      path: '/$id'
      fullPath: '/grupos/$id'
      preLoaderRoute: typeof AppGruposIdRouteImport
      parentRoute: typeof AppGruposRoute
    }
    '/_app/mentorias/': {
      id: '/_app/mentorias/'
      path: '/'
      fullPath: '/mentorias/'
      preLoaderRoute: typeof AppMentoriasIndexRouteImport
      parentRoute: typeof AppMentoriasRoute
    }
    '/_app/mentorias/$id': {
      id: '/_app/mentorias/$id'
      path: '/$id'
      fullPath: '/mentorias/$id'
      preLoaderRoute: typeof AppMentoriasIdRouteImport
      parentRoute: typeof AppMentoriasRoute
    }
    '/_app/mentorias/agendamento': {
      id: '/_app/mentorias/agendamento'
      path: '/agendamento'
      fullPath: '/mentorias/agendamento'
      preLoaderRoute: typeof AppMentoriasAgendamentoRouteImport
      parentRoute: typeof AppMentoriasRoute
    }
    '/_app/pessoas/': {
      id: '/_app/pessoas/'
      path: '/'
      fullPath: '/pessoas/'
      preLoaderRoute: typeof AppPessoasIndexRouteImport
      parentRoute: typeof AppPessoasRoute
    }
    '/_app/pessoas/$id': {
      id: '/_app/pessoas/$id'
      path: '/$id'
      fullPath: '/pessoas/$id'
      preLoaderRoute: typeof AppPessoasIdRouteImport
      parentRoute: typeof AppPessoasRoute
    }
    '/_app/respostas/': {
      id: '/_app/respostas/'
      path: '/'
      fullPath: '/respostas/'
      preLoaderRoute: typeof AppRespostasIndexRouteImport
      parentRoute: typeof AppRespostasRoute
    }
    '/_app/testes/': {
      id: '/_app/testes/'
      path: '/'
      fullPath: '/testes/'
      preLoaderRoute: typeof AppTestesIndexRouteImport
      parentRoute: typeof AppTestesRoute
    }
    '/aluno/classroom/': {
      id: '/aluno/classroom/'
      path: '/classroom'
      fullPath: '/aluno/classroom/'
      preLoaderRoute: typeof AlunoClassroomIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/classroom/$treinamentoId': {
      id: '/aluno/classroom/$treinamentoId'
      path: '/classroom/$treinamentoId'
      fullPath: '/aluno/classroom/$treinamentoId'
      preLoaderRoute: typeof AlunoClassroomTreinamentoIdRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/educacao/': {
      id: '/aluno/educacao/'
      path: '/educacao'
      fullPath: '/aluno/educacao/'
      preLoaderRoute: typeof AlunoEducacaoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/educacao/$trackId': {
      id: '/aluno/educacao/$trackId'
      path: '/educacao/$trackId'
      fullPath: '/aluno/educacao/$trackId'
      preLoaderRoute: typeof AlunoEducacaoTrackIdRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/api/cron/lembretes': {
      id: '/api/cron/lembretes'
      path: '/api/cron/lembretes'
      fullPath: '/api/cron/lembretes'
      preLoaderRoute: typeof ApiCronLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/icone/$tamanho': {
      id: '/api/icone/$tamanho'
      path: '/api/icone/$tamanho'
      fullPath: '/api/icone/$tamanho'
      preLoaderRoute: typeof ApiIconeTamanhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentor-foto/$slug': {
      id: '/api/mentor-foto/$slug'
      path: '/api/mentor-foto/$slug'
      fullPath: '/api/mentor-foto/$slug'
      preLoaderRoute: typeof ApiMentorFotoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/testes/$versionId/editar': {
      id: '/_app/testes/$versionId/editar'
      path: '/$versionId/editar'
      fullPath: '/testes/$versionId/editar'
      preLoaderRoute: typeof AppTestesVersionIdEditarRouteImport
      parentRoute: typeof AppTestesRoute
    }
    '/_app/testes/$versionId/respostas': {
      id: '/_app/testes/$versionId/respostas'
      path: '/$versionId/respostas'
      fullPath: '/testes/$versionId/respostas'
      preLoaderRoute: typeof AppTestesVersionIdRespostasRouteImport
      parentRoute: typeof AppTestesRoute
    }
    '/api/public/action-plan/$id': {
      id: '/api/public/action-plan/$id'
      path: '/api/public/action-plan/$id'
      fullPath: '/api/public/action-plan/$id'
      preLoaderRoute: typeof ApiPublicActionPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/assessment/$id': {
      id: '/api/public/assessment/$id'
      path: '/api/public/assessment/$id'
      fullPath: '/api/public/assessment/$id'
      preLoaderRoute: typeof ApiPublicAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkin/$aulaId': {
      id: '/api/public/checkin/$aulaId'
      path: '/api/public/checkin/$aulaId'
      fullPath: '/api/public/checkin/$aulaId'
      preLoaderRoute: typeof ApiPublicCheckinAulaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/invite/$id': {
      id: '/api/public/invite/$id'
      path: '/api/public/invite/$id'
      fullPath: '/api/public/invite/$id'
      preLoaderRoute: typeof ApiPublicInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/report-bateria/$id': {
      id: '/api/public/report-bateria/$id'
      path: '/api/public/report-bateria/$id'
      fullPath: '/api/public/report-bateria/$id'
      preLoaderRoute: typeof ApiPublicReportBateriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/report/$id': {
      id: '/api/public/report/$id'
      path: '/api/public/report/$id'
      fullPath: '/api/public/report/$id'
      preLoaderRoute: typeof ApiPublicReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/response/$id': {
      id: '/api/public/response/$id'
      path: '/api/public/response/$id'
      fullPath: '/api/public/response/$id'
      preLoaderRoute: typeof ApiPublicResponseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/testes/$versionId/pdf/$responseId': {
      id: '/_app/testes/$versionId/pdf/$responseId'
      path: '/$versionId/pdf/$responseId'
      fullPath: '/testes/$versionId/pdf/$responseId'
      preLoaderRoute: typeof AppTestesVersionIdPdfResponseIdRouteImport
      parentRoute: typeof AppTestesRoute
    }
  }
}

interface AppEnviosRouteChildren {
  AppEnviosNovoRoute: typeof AppEnviosNovoRoute
  AppEnviosIndexRoute: typeof AppEnviosIndexRoute
}

const AppEnviosRouteChildren: AppEnviosRouteChildren = {
  AppEnviosNovoRoute: AppEnviosNovoRoute,
  AppEnviosIndexRoute: AppEnviosIndexRoute,
}

const AppEnviosRouteWithChildren = AppEnviosRoute._addFileChildren(
  AppEnviosRouteChildren,
)

interface AppGruposRouteChildren {
  AppGruposIdRoute: typeof AppGruposIdRoute
  AppGruposIndexRoute: typeof AppGruposIndexRoute
}

const AppGruposRouteChildren: AppGruposRouteChildren = {
  AppGruposIdRoute: AppGruposIdRoute,
  AppGruposIndexRoute: AppGruposIndexRoute,
}

const AppGruposRouteWithChildren = AppGruposRoute._addFileChildren(
  AppGruposRouteChildren,
)

interface AppMentoriasRouteChildren {
  AppMentoriasIdRoute: typeof AppMentoriasIdRoute
  AppMentoriasAgendamentoRoute: typeof AppMentoriasAgendamentoRoute
  AppMentoriasIndexRoute: typeof AppMentoriasIndexRoute
}

const AppMentoriasRouteChildren: AppMentoriasRouteChildren = {
  AppMentoriasIdRoute: AppMentoriasIdRoute,
  AppMentoriasAgendamentoRoute: AppMentoriasAgendamentoRoute,
  AppMentoriasIndexRoute: AppMentoriasIndexRoute,
}

const AppMentoriasRouteWithChildren = AppMentoriasRoute._addFileChildren(
  AppMentoriasRouteChildren,
)

interface AppPessoasRouteChildren {
  AppPessoasIdRoute: typeof AppPessoasIdRoute
  AppPessoasIndexRoute: typeof AppPessoasIndexRoute
}

const AppPessoasRouteChildren: AppPessoasRouteChildren = {
  AppPessoasIdRoute: AppPessoasIdRoute,
  AppPessoasIndexRoute: AppPessoasIndexRoute,
}

const AppPessoasRouteWithChildren = AppPessoasRoute._addFileChildren(
  AppPessoasRouteChildren,
)

interface AppRespostasRouteChildren {
  AppRespostasIndexRoute: typeof AppRespostasIndexRoute
}

const AppRespostasRouteChildren: AppRespostasRouteChildren = {
  AppRespostasIndexRoute: AppRespostasIndexRoute,
}

const AppRespostasRouteWithChildren = AppRespostasRoute._addFileChildren(
  AppRespostasRouteChildren,
)

interface AppTestesRouteChildren {
  AppTestesIndexRoute: typeof AppTestesIndexRoute
  AppTestesVersionIdEditarRoute: typeof AppTestesVersionIdEditarRoute
  AppTestesVersionIdRespostasRoute: typeof AppTestesVersionIdRespostasRoute
  AppTestesVersionIdPdfResponseIdRoute: typeof AppTestesVersionIdPdfResponseIdRoute
}

const AppTestesRouteChildren: AppTestesRouteChildren = {
  AppTestesIndexRoute: AppTestesIndexRoute,
  AppTestesVersionIdEditarRoute: AppTestesVersionIdEditarRoute,
  AppTestesVersionIdRespostasRoute: AppTestesVersionIdRespostasRoute,
  AppTestesVersionIdPdfResponseIdRoute: AppTestesVersionIdPdfResponseIdRoute,
}

const AppTestesRouteWithChildren = AppTestesRoute._addFileChildren(
  AppTestesRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppColaboradoresRoute: typeof AppColaboradoresRoute
  AppComunidadesRoute: typeof AppComunidadesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEnviosRoute: typeof AppEnviosRouteWithChildren
  AppGruposRoute: typeof AppGruposRouteWithChildren
  AppMentoresRoute: typeof AppMentoresRoute
  AppMentoriasRoute: typeof AppMentoriasRouteWithChildren
  AppPessoasRoute: typeof AppPessoasRouteWithChildren
  AppRespostasRoute: typeof AppRespostasRouteWithChildren
  AppTestesRoute: typeof AppTestesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppClassroomTreinamentoIdRoute: typeof AppClassroomTreinamentoIdRoute
  AppEducacaoTrackIdRoute: typeof AppEducacaoTrackIdRoute
  AppClassroomIndexRoute: typeof AppClassroomIndexRoute
  AppEducacaoIndexRoute: typeof AppEducacaoIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppColaboradoresRoute: AppColaboradoresRoute,
  AppComunidadesRoute: AppComunidadesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEnviosRoute: AppEnviosRouteWithChildren,
  AppGruposRoute: AppGruposRouteWithChildren,
  AppMentoresRoute: AppMentoresRoute,
  AppMentoriasRoute: AppMentoriasRouteWithChildren,
  AppPessoasRoute: AppPessoasRouteWithChildren,
  AppRespostasRoute: AppRespostasRouteWithChildren,
  AppTestesRoute: AppTestesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppClassroomTreinamentoIdRoute: AppClassroomTreinamentoIdRoute,
  AppEducacaoTrackIdRoute: AppEducacaoTrackIdRoute,
  AppClassroomIndexRoute: AppClassroomIndexRoute,
  AppEducacaoIndexRoute: AppEducacaoIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AlunoRouteChildren {
  AlunoAgendaRoute: typeof AlunoAgendaRoute
  AlunoComunidadeRoute: typeof AlunoComunidadeRoute
  AlunoCriarSenhaRoute: typeof AlunoCriarSenhaRoute
  AlunoGruposRoute: typeof AlunoGruposRoute
  AlunoMentoriasRoute: typeof AlunoMentoriasRoute
  AlunoPerfilRoute: typeof AlunoPerfilRoute
  AlunoRankingRoute: typeof AlunoRankingRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
  AlunoClassroomTreinamentoIdRoute: typeof AlunoClassroomTreinamentoIdRoute
  AlunoEducacaoTrackIdRoute: typeof AlunoEducacaoTrackIdRoute
  AlunoClassroomIndexRoute: typeof AlunoClassroomIndexRoute
  AlunoEducacaoIndexRoute: typeof AlunoEducacaoIndexRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoAgendaRoute: AlunoAgendaRoute,
  AlunoComunidadeRoute: AlunoComunidadeRoute,
  AlunoCriarSenhaRoute: AlunoCriarSenhaRoute,
  AlunoGruposRoute: AlunoGruposRoute,
  AlunoMentoriasRoute: AlunoMentoriasRoute,
  AlunoPerfilRoute: AlunoPerfilRoute,
  AlunoRankingRoute: AlunoRankingRoute,
  AlunoIndexRoute: AlunoIndexRoute,
  AlunoClassroomTreinamentoIdRoute: AlunoClassroomTreinamentoIdRoute,
  AlunoEducacaoTrackIdRoute: AlunoEducacaoTrackIdRoute,
  AlunoClassroomIndexRoute: AlunoClassroomIndexRoute,
  AlunoEducacaoIndexRoute: AlunoEducacaoIndexRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AlunoRoute: AlunoRouteWithChildren,
  AuthRoute: AuthRoute,
  CriarSenhaRoute: CriarSenhaRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AgendarSlugRoute: AgendarSlugRoute,
  ApiManifestRoute: ApiManifestRoute,
  ApiMarcaRoute: ApiMarcaRoute,
  BateriaAssessmentIdRoute: BateriaAssessmentIdRoute,
  CheckinAulaIdRoute: CheckinAulaIdRoute,
  ConviteEquipeTokenRoute: ConviteEquipeTokenRoute,
  ConviteLinkIdRoute: ConviteLinkIdRoute,
  RelatorioBateriaAssessmentIdRoute: RelatorioBateriaAssessmentIdRoute,
  RelatorioResponseIdRoute: RelatorioResponseIdRoute,
  ResponderResponseIdRoute: ResponderResponseIdRoute,
  SessaoIdRoute: SessaoIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiCronLembretesRoute: ApiCronLembretesRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiIconeTamanhoRoute: ApiIconeTamanhoRoute,
  ApiMentorFotoSlugRoute: ApiMentorFotoSlugRoute,
  ApiPublicActionPlanIdRoute: ApiPublicActionPlanIdRoute,
  ApiPublicAssessmentIdRoute: ApiPublicAssessmentIdRoute,
  ApiPublicCheckinAulaIdRoute: ApiPublicCheckinAulaIdRoute,
  ApiPublicInviteIdRoute: ApiPublicInviteIdRoute,
  ApiPublicReportBateriaIdRoute: ApiPublicReportBateriaIdRoute,
  ApiPublicReportIdRoute: ApiPublicReportIdRoute,
  ApiPublicResponseIdRoute: ApiPublicResponseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
