/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPessoasRouteImport } from './routes/_app.pessoas'
import { Route as AppPessoasIdRouteImport } from './routes/_app.pessoas.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasRoute = AppPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasIdRoute = AppPessoasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPessoasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/pessoas': typeof AppPessoasRouteWithChildren
  '/pessoas/$id': typeof AppPessoasIdRoute
}
export interface FileRoutesByTo {
  '/pessoas': typeof AppPessoasRouteWithChildren
  '/': typeof AppIndexRoute
  '/pessoas/$id': typeof AppPessoasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/pessoas': typeof AppPessoasRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/pessoas/$id': typeof AppPessoasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pessoas' | '/pessoas/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/pessoas' | '/' | '/pessoas/$id'
  id: '__root__' | '/_app' | '/_app/pessoas' | '/_app/' | '/_app/pessoas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pessoas': {
      id: '/_app/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof AppPessoasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pessoas/$id': {
      id: '/_app/pessoas/$id'
      path: '/$id'
      fullPath: '/pessoas/$id'
      preLoaderRoute: typeof AppPessoasIdRouteImport
      parentRoute: typeof AppPessoasRoute
    }
  }
}

interface AppPessoasRouteChildren {
  AppPessoasIdRoute: typeof AppPessoasIdRoute
}

const AppPessoasRouteChildren: AppPessoasRouteChildren = {
  AppPessoasIdRoute: AppPessoasIdRoute,
}

const AppPessoasRouteWithChildren = AppPessoasRoute._addFileChildren(
  AppPessoasRouteChildren,
)

interface AppRouteChildren {
  AppPessoasRoute: typeof AppPessoasRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPessoasRoute: AppPessoasRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
